# Time in seconds between each dispatch cycle
dispatch_interval = 5

[smtp]
net = "tcp"
host = "0.0.0.0"
port = 1025

[sender]
provider = "ses"

[sender.settings]
region = "us-east-1"

[auth]
auth_users = ["user1:pass1", "user2:pass2"]
